name: Yocto Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show workspace info
        run: |
          echo "Workspace: $GITHUB_WORKSPACE"
          ls -al

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            gawk wget git diffstat unzip texinfo gcc build-essential \
            chrpath socat cpio python3 python3-pip python3-pexpect \
            xz-utils debianutils iputils-ping file tree

      - name: Clone poky (kirkstone)
        run: |
          git clone --depth 1 -b kirkstone git://git.yoctoproject.org/poky

      # Cache downloads (big speed improvement)
      - name: Cache downloads
        uses: actions/cache@v4
        with:
          path: poky/downloads
          key: yocto-downloads-${{ runner.os }}

      # Cache sstate (huge speed improvement)
      - name: Cache sstate
        uses: actions/cache@v4
        with:
          path: poky/sstate-cache
          key: yocto-sstate-${{ runner.os }}

      - name: Setup build environment
        run: |
          cd poky
          source oe-init-build-env build

          echo 'DL_DIR = "${TOPDIR}/../downloads"' >> conf/local.conf
          echo 'SSTATE_DIR = "${TOPDIR}/../sstate-cache"' >> conf/local.conf
          echo 'BB_NUMBER_THREADS = "4"' >> conf/local.conf
          echo 'PARALLEL_MAKE = "-j4"' >> conf/local.conf

          bitbake-layers add-layer ../../meta-mathutils

      - name: Build mathutils
        run: |
          cd poky
          source oe-init-build-env build
          bitbake mathutils

      - name: Locate binary & Run tests
        run: |
          sudo ln -sf /lib64/ld-linux-x86-64.so.2 /lib/ld-linux-x86-64.so.2
          BINARY=$(find poky/build/tmp/work -path "*/image/usr/bin/mathutils_app" | head -n 1)
          echo "Binary found at: $BINARY"
          echo "BINARY=$BINARY" >> $GITHUB_ENV
          chmod +x $BINARY
          $BINARY

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: mathutils_app
          path: ${{ env.BINARY }}
